export const GET_DATA_AUTHORS = "authors/GET_DATA_AUTHORS";
export const GET_DATA_AUTHORS_LOADING = "authors/GET_DATA_AUTHORS_LOADING";
export const GET_DATA_AUTHORS_ERRORMESSAGE =
  "authors/GET_DATA_AUTHORS_ERRORMESSAGE";
